#:schema https://raw.githubusercontent.com/yamoling/lle/refs/heads/master/resources/lle_toml_schema.json
exits = [{ i_min = 8, j_min = 7 }]
starts = [{ i_max = 5, j_max = 5 }]
n_agents = 2
world_string = """
@ @ @ @ @ @ @ @ @ @ @ @ @
@ . . . . . @ . . . . . @
@ . . . . . @ . . . . . @
@ . . . . . . . . . . . @
@ . . . . . @ . . . . . @
@ . . . . . @ . . . . . @
@ @ . @ @ @ @ . . . . . @
@ . . . . . @ @ @ . @ @ @
@ . . . . . @ . . . . . @
@ . . . . . @ . . . . . @
@ . . . . . . . . . . . @
@ . . . . . @ . . . . . @
@ @ @ @ @ @ @ @ @ @ @ @ @
"""
